import Head from "next/head";
import Link from "next/link";
const { Client } = require("@notionhq/client");
const notion = new Client({ auth: process.env.NOTION_API_KEY });

export default function Home({ list }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto max-w-3xl px-12 mt-40">
        <h1 className="text-6xl font-bold">Fraction Design</h1>
        <ul className="mt-7 transform -translate-x-5">
          {list.map((item) => (
            <li className="hover:bg-gray-200 transition-colors" key={item.id}>
              <Link href={`/${item.properties.Slug.rich_text[0].plain_text}`}>
                <a className="block px-5 py-4">
                  <h2 className="text-xl font-medium">
                    {item.properties.Name.title[0].plain_text}
                  </h2>
                  <p className="text-gray-500 flex items-center spax">
                    {item.properties.Author.created_by.name}
                  </p>
                </a>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const list = await notion.databases.query({
    database_id: process.env.NOTION_DATABASE,
  });

  return {
    props: {
      list: list.results,
    },
    revalidate: 1,
  };
}
